
#**Machine Learning And Data Science Laboratory(410501)**

#BE Sem I Honors in ML&DS

#Academic Year: 2022-23

#Lab Assignment No.3



**NAME : CHITTARANJAN RATHOD**

**ROLL NO : 42457**

**PRN NO : 72017193J**

**ABC ID : 129-879-043-197**

**BRANCH : E&TC**

**COLLEGE : PICT**

In [ ]:
import numpy as np 
from random import randint
#inputs 

X=np.array([[1,1,1],[1,-1,1],[-1,1,1],[-1,-1,1]])
#output
Y_ad=np.array([[1],[-1],[-1],[-1]])
Y_o=np.array([[1],[1],[1],[-1]])



print('input is:')
print(X)
print('output for And Gate is: ')
print(Y_ad)
print('output for Or Gate is: ')
print(Y_ad)
weights_ad=np.zeros((3))
weights_o=np.zeros((3))
print(weights_ad)


# update weight for and gate /logic
def update_weight_ad(X,Y,weights):
    for i in range(4):
         
        weights=weights+X[i]*Y[i]
        
        #print weights
        slope =-(weights[0]/weights[1])
        c=-(weights[2]/weights[0])
        if slope<0 and weights[0]>0:
            weights_main=weights
        
    return weights_main
            
def update_weight_o(X,Y,weights):
    for i in range(4):
         
        weights=weights+X[i]*Y[i]
        
        #print weights
        slope =-(weights[0]/weights[1])
        c=-(weights[2]/weights[0])
        if slope<0 and weights[0]>0:
            weights_main=weights
        
    return weights_main
        
        
    
weights_ad=update_weight_ad(X,Y_ad,weights_ad)
weights_o=update_weight_o(X,Y_o,weights_o)


print('Checking after learning selectg a input')
rand_int=int(input('Enter the test case no you want to try'))
print('Select a logic you also want  to check')
logicgate=input()
print(weights_ad)
print('selected input is %d '%rand_int)
print(X[rand_int])
def check_learning(X,weights,rand_int):
    Yin=0
    for i in range(3):
        Yin+=X[rand_int,i]*weights[i]
    if Yin<0:
        Yin=-1
    else:
        Yin=1
    return Yin


if logicgate=='a' or logicgate=='A':
    weights_in=weights_ad
else:
    weights_in=weights_o
Yin=check_learning(X,weights_in,rand_int)
print(Yin)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in double_scalars
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:43: RuntimeWarning: divide by zero encountered in double_scalars


input is:
[[ 1  1  1]
 [ 1 -1  1]
 [-1  1  1]
 [-1 -1  1]]
output for And Gate is: 
[[ 1]
 [-1]
 [-1]
 [-1]]
output for Or Gate is: 
[[ 1]
 [-1]
 [-1]
 [-1]]
[0. 0. 0.]
Checking after learning selectg a input
Enter the test case no you want to try2
Select a logic you also want  to check
A
[ 2.  2. -2.]
selected input is 2 
[-1  1  1]
-1
